# This is an example Yaml file
define(ROOT, /home)
define(IMAGE, ROOT/Image)
define(PROTOCOL, http)
define(SERVER, www.test.com)
define(PORT, 8080)
define(TEST, PROTOCOL://SERVER:PORT_IMAGE-ROOT+IMAGE)
define(ott, 345)
www:
  - ott
  - list-item1
  - list-item2
xxx:
  yyy: zzz
  zzz: foo
  long: |
        This is a long
        text shown as a string
dirs:
  root: 'ROOT'
  mydir: 'IMAGE/my/dir'

root_url: '1 -> PROTOCOL://SERVER:$PORT'
root_url2: '2 -> PROTOCOL://SERVER:PORT'